spring.application.name=sm_rest_service

#NOTE: 
#Do not commit credentials in your project repository!!!
#In a real-world project, credentials and secrets are vaulted.
#This is just a demo project.
spring.datasource.url=jdbc:mysql://localhost:3306/social-media-database
spring.datasource.username=social-media-user
spring.datasource.password=dummypassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect